# Generated by Django 3.2.10 on 2021-12-08 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211208_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38ca7488-1492-4c8e-9331-652480dd0811'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e2f25ed-8a11-4b29-990a-4e5eafb793d4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2d5bf6e1-baba-4251-a3cf-2cfe8a3b5f76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
